package ci.dgmp.sigomap.authmodule.model.constants;

public class AuthActions
{
    public static final String ADD_PRV_TO_MENU = "Ajout de privilège(s) à un menu";
    public static final String CREATE_MENU = "Création d'un nouveau menu";
    public static final String DELETE_MENU = "Suppression d'un menu";
    public static final String UPDATE_MENU = "Modification d'un menu";
    public static final String RMV_PRV_TO_MENU = "Suppression de privilège(s) à un menu";
    public static final String CREATE_USER = "Cr&ation d'un utilisateur";
    public static final String CREATE_MEMBER = "Ajout d'un nouveau membre à une association";
    public static final String LOGIN = "Login";
    public static final String LOGOUT = "Logout";
    public static final String REFRESH_TOKEN = "Refresh token";
    public static final String ACTIVATE_USER_ACCOUNT = "Activation de compte";
    public static final String LOCK_USER_ACCOUNT = "Restriction de compte";
    public static final String UNLOCK_USER_ACCOUNT = "Restauration de compte";
    public static final String UPDATE_USER = "Modification d'un utilisateur";
    public static final String CHANGE_PASSWORD = "Changement de mot de passe";
    public static final String REINIT_PASSWORD = "Réinitialisation de mot de passe";
    public static final String CREATE_ACCOUT_TOKEN = "Création d'un token de sécurité";
    public static final String UPDATE_ACCOUT_TOKEN = "Mise à jour d'un token de sécurité";
    public static final String SEND_ACCOUNT_ACTIVATION_EMAIL = "Envoie d'un email d'activation de compte";
    public static final String SEND_REINIT_PASSWORD_EMAIL = "Envoie d'un mail de réinitialisation de mot de passe";
    public static final String CLICK_LINK = "Click sur un lien envoyé par mail";
    public static final String CREATE_PRV = "Création d'un privilège";
    public static final String CREATE_ROLE = "Création d'un rôle";
    public static final String CREATE_FNC = "Création d'une fonction";
    public static final String ADD_ROLE_TO_FNC = "Ajout d'un rôle à une fonction";
    public static final String ADD_PRV_TO_FNC = "Ajout d'un privilège à une fonction";
    public static final String SET_FNC_AS_NONE_DEFAULT = "Suppression du caractère par défaut d'une fonction";
    public static final String SET_FNC_AS_DEFAULT = "Définition d'une fonction en tant que fonction par défaut";
    public static final String SET_USER_DEFAULT_FNC_ID = "Changement de la fonction par défaut d'un utilisateur";
    public static final String REVOKE_FNC = "Révocation d'une fonction";
    public static final String RESTORE_FNC = "Restauration d'une fonction";
    public static final String REMOVE_ROLE_TO_FNC = "Retrait d'un rôle à une fonction";
    public static final String RESTORE_ROLE_TO_FNC = "Restaurer le role d'une fonction";
    public static final String CHANGE_ROLE_TO_FNC_VALIDITY_PERIOD = "Changement de la période de validité d'une assignation de rôle à fonction";
    public static final String ASSIGNATION_ACTIVATED_AND_VALIDITY_PERIOD_CHANGED = "Restauration et changement de la période de validité d'une assignation de rôle à fonction";
    public static final String PRV_TO_ROL_ACTIVATED_AND_VALIDITY_PERIOD_CHANGED = "Restauration du privilège d'un rôle et changement de la période de validité";
    public static final String REMOVE_PRV_TO_FNC = "Retrait d'un privilège à une fonction";
    public static final String REVOKE_PRV_TO_FNC = "Revocation d'un privilège à une fonction";
    public static final String RESTORE_PRV_TO_FNC = "Restauration d'un privilège à un rôle";
    public static final String CHANGE_PRV_TO_FNC_VALIDITY_PERIOD = "Changement de la période de validité d'une assignation de rôle privilège à fonction";
    public static final String REMOVE_PRV_TO_ROL = "Retrait d'un privilège à un rôle";
    public static final String CHANGE_PRV_TO_ROL_VALIDITY_PERIOD = "Changement de la période de validité de l'assignation d'un privilège à une rôle";
    public static final String RESTORE_PRV_TO_ROL = "Restauration du privilège d'un rôle";
    public static final String ADD_PRV_TO_ROL = "Ajout d'un privilège à un rôle";
    public static final String UPDATE_ROL = "Modification de rôle";
    public static final String SET_TOKEN_AS_ALREADY_USED = "Marquage d'un token comme déjà utilisé";
    public static final String UPDATE_FUNCTION = "Mise à jour des informations d'une fonction";
    public static final String UPDATE_PRV = "Mise à jour d'un privilège";
    public static final String CREATE_USER_AND_FUNCTIONS = "Création d'un utilisateur et ses fonctions";
    public static final String UPDATE_USER_AND_FUNCTIONS = "Modification d'un utilidsateur et d'une fonction";
}
